# Tirgul 3

## Add nice equations using LaTEX syntax in Markdown
### Sphere or Quadratic equations::
$ x^2 + y^2 = z^2 \\$
$ \\ x_1,_2 =  \frac{- b\pm \sqrt{b^2-4ac}}{2a} $

# master chef
# https://www.facebook.com/MicrosoftRnDil/videos/1090576338109340/

In [2]:
# get file from web
import pandas as pd
url = "https://data.humdata.org/hxlproxy/api/data-preview.csv?url=https%3A%2F%2Fraw.githubusercontent.com%2FCSSEGISandData%2FCOVID-19%2Fmaster%2Fcsse_covid_19_data%2Fcsse_covid_19_time_series%2Ftime_series_covid19_deaths_global.csv"
cuvid19Deaths = pd.read_csv(url)
cuvid19Deaths.head()

Province/State Country/Region       Lat       Long  1/22/20  1/23/20  \
0            NaN    Afghanistan  33.93911  67.709953        0        0   
1            NaN        Albania  41.15330  20.168300        0        0   
2            NaN        Algeria  28.03390   1.659600        0        0   
3            NaN        Andorra  42.50630   1.521800        0        0   
4            NaN         Angola -11.20270  17.873900        0        0   

   1/24/20  1/25/20  1/26/20  1/27/20  ...  4/3/21  4/4/21  4/5/21  4/6/21  \
0        0        0        0        0  ...    2496    2497    2508    2512   
1        0        0        0        0  ...    2256    2265    2274    2283   
2        0        0        0        0  ...    3102    3105    3108    3112   
3        0        0        0        0  ...     117     117     117     117   
4        0        0        0        0  ...     540     542     543     547   

   4/7/21  4/8/21  4/9/21  4/10/21  4/11/21  4/12/21  
0    2512    2516    2521     2521     2521     2529  
1    2291    2297    2304     2310     2317     2321  
2    3116    3119    3123     3126     3130     3134  
3     119     120     120      120      120      121  
4     547     549     549      550      553      554  

[5 rows x 451 columns]

In [8]:
# get Israel data
cuvid19Deaths[cuvid19Deaths['Country/Region'].str.contains("is")]

Province/State         Country/Region        Lat       Long  1/22/20  \
0              NaN            Afghanistan  33.939110  67.709953        0   
139            NaN          Guinea-Bissau  11.803700 -15.180400        0   
203            NaN               Pakistan  30.375300  69.345100        0   
215            NaN  Saint Kitts and Nevis  17.357822 -62.782998        0   
241            NaN             Tajikistan  38.861000  71.276100        0   
247            NaN                Tunisia  33.886917   9.537499        0   
266            NaN             Uzbekistan  41.377491  64.585262        0   

     1/23/20  1/24/20  1/25/20  1/26/20  1/27/20  ...  4/3/21  4/4/21  4/5/21  \
0          0        0        0        0        0  ...    2496    2497    2508   
139        0        0        0        0        0  ...      65      66      66   
203        0        0        0        0        0  ...   14778   14821   14924   
215        0        0        0        0        0  ...       0       0       0   
241        0        0        0        0        0  ...      90      90      90   
247        0        0        0        0        0  ...    8931    8965    8993   
266        0        0        0        0        0  ...     630     631     631   

     4/6/21  4/7/21  4/8/21  4/9/21  4/10/21  4/11/21  4/12/21  
0      2512    2512    2516    2521     2521     2521     2529  
139      66      66      66      66       66       66       66  
203   15026   15124   15229   15329    15443    15501    15619  
215       0       0       0       0        0        0        0  
241      90      90      90      90       90       90       90  
247    9039    9087    9136    9179     9235     9293     9332  
266     632     633     634     634      634      634      634  

[7 rows x 451 columns]

In [10]:
data = pd.read_csv('titanic_short.csv')
data.head()

pclass  survived      age     sex
0    1st         1  29.0000  female
1    1st         0   2.0000  female
2    1st         0  30.0000    male
3    1st         0  25.0000  female
4    1st         1   0.9167    male

In [11]:
data['age']

0     29.0000
1      2.0000
2     30.0000
3     25.0000
4      0.9167
5     47.0000
6     63.0000
7     39.0000
8     58.0000
9     71.0000
10    47.0000
11    19.0000
12        NaN
13        NaN
14        NaN
15    50.0000
16    24.0000
17    36.0000
18    37.0000
19        NaN
20    26.0000
21    25.0000
22        NaN
23    19.0000
24    28.0000
25        NaN
26    39.0000
27    30.0000
28    58.0000
29        NaN
Name: age, dtype: float64

In [15]:
# is null - isna
dataIsNull = pd.isnull(data['age'])
data[['age','sex']].isnull().sum()

age    7
sex    0
dtype: int64

In [18]:
# isna is exactly the same (due to historical reasons related to 'R' language)
dataIsna = pd.isna(data['age'])
dataIsna

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13     True
14     True
15    False
16    False
17    False
18    False
19     True
20    False
21    False
22     True
23    False
24    False
25     True
26    False
27    False
28    False
29     True
Name: age, dtype: bool

In [19]:
# we can present the data at these null rows
filteredData = data[pd.isna(data['age'])]
filteredData

pclass  survived  age     sex
12    1st         1  NaN  female
13    1st         1  NaN    male
14    1st         0  NaN    male
19    1st         1  NaN  female
22    1st         1  NaN    male
25    1st         0  NaN    male
29    1st         0  NaN    male

In [23]:
# What if we want to only the cell with no null:
# we could us the ~ operate
filteredData = data[~pd.isna(data['age'])]
filteredData

pclass  survived      age     sex
0     1st         1  29.0000  female
1     1st         0   2.0000  female
2     1st         0  30.0000    male
3     1st         0  25.0000  female
4     1st         1   0.9167    male
5     1st         1  47.0000    male
6     1st         1  63.0000  female
7     1st         0  39.0000    male
8     1st         1  58.0000  female
9     1st         0  71.0000    male
10    1st         0  47.0000    male
11    1st         1  19.0000  female
15    1st         1  50.0000  female
16    1st         0  24.0000    male
17    1st         0  36.0000    male
18    1st         1  37.0000    male
20    1st         1  26.0000    male
21    1st         0  25.0000    male
23    1st         1  19.0000  female
24    1st         1  28.0000    male
26    1st         1  39.0000    male
27    1st         1  30.0000  female
28    1st         1  58.0000  female

In [24]:
# or the notnull command
filteredData = data[pd.notnull(data['age'])]
filteredData.head(13)

pclass  survived      age     sex
0     1st         1  29.0000  female
1     1st         0   2.0000  female
2     1st         0  30.0000    male
3     1st         0  25.0000  female
4     1st         1   0.9167    male
5     1st         1  47.0000    male
6     1st         1  63.0000  female
7     1st         0  39.0000    male
8     1st         1  58.0000  female
9     1st         0  71.0000    male
10    1st         0  47.0000    male
11    1st         1  19.0000  female
15    1st         1  50.0000  female

In [26]:
# Mean
dataAge = filteredData['age']
dataAge.mean()

34.90942173913044

In [27]:
dataAge.min()

0.9167

In [28]:
dataAge.max()

71.0

In [29]:
dataAge.median()

30.0

## Numpy
Matrices and much more, this is where the fun begins..

[Numpy official docs](https://numpy.org/doc/stable/reference/index.html)

In [50]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5],[3,4,5,6,7],[1,2,3,4,5]])
print(arr.shape)





(3, 5)


ValueError: shapes (3,5) and (3,5) not aligned: 5 (dim 1) != 3 (dim 0)

In [43]:
#### vector multiplication (AKA dot producdt)
print("arr.dot(arr)\t=",arr.dot(arr))
# or by 
print("arr@arr\t\t=",arr@arr)


ValueError: shapes (3,5) and (3,5) not aligned: 5 (dim 1) != 3 (dim 0)

In [52]:
# create ones matrix of specific size:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
# self excercise: create zeros matrix of specific size 4X3:






In [53]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
# The I matrix
d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [41]:
# self excercise: create the following 3X3 diagonal matrix
#  [1., 0., 0.],
#  [0., 2., 0.],
#  [0., 0., 3.]








In [42]:
print([1,2,3]*np.eye(3))

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


In [55]:
# Another Way
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [44]:
# random
e = np.random.random((2,4)) 
print(e)

[[0.74738624 0.61785783 0.22894666 0.82370343]
 [0.45945422 0.05077788 0.30786927 0.38762231]]


In [45]:
# append
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([11, 12, 13, 14, 15])
arr3 = np.append(arr1,arr2)
print(arr3)


[ 1  2  3  4  5 11 12 13 14 15]


In [46]:
# we can add arrays of same shape
print(arr1+arr2)

[12 14 16 18 20]


In [47]:
# However arrays must have same size
arr3 = np.array([1,2])
print(arr1+arr3) # ERROR

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

In [ ]:
# self excercise: Assume hypothethical case where you wish for each student to calculate average of the highest 5 grades out of 6 student's assignment
# step 1. generate 10X6 random integer numbers between 70 to 100 to represent students grades
# step 2. calculate mean of top 5 grades for each student








In [66]:
numCols = 6
grades = np.random.randint(0,100,size=(10,5))
print(grades)
grades[0:10].mean(axis=0)

[[58 84  2 18 96]
 [72 92 42 10 41]
 [62 36 91 76 22]
 [56 58 34 97 83]
 [68 76 59 28 98]
 [19 14 49 98 52]
 [56 45 59 49 54]
 [88 31 29 68  2]
 [71  1 10  2 14]
 [ 1 10 24 15  3]]


array([55.1, 44.7, 39.9, 46.1, 46.5])

In [38]:
top5Avg = (grades.sum(axis=1)-grades.min(axis=1)) / (numCols-1)
top5Avg
top5Avg = top5Avg.reshape(len(top5Avg),1) # for display purpose
print(top5Avg)

[[83. ]
 [88.4]
 [88. ]
 [82.8]
 [79.6]
 [88.6]
 [89.2]
 [86.2]
 [85.8]
 [86.2]]
