# Trigul 2
 A deeper dive into *Pandas* and *Numpy*

In [1]:
# cmd view point denoted by ! sign
!pip install numpy
!pip install pandas

In [2]:

# read file using pandas
# pandas is a fast, powerful, flexible and easy to use open source data analysis in python
import pandas as pd
data = pd.read_csv('titanic_short.csv')
### The data read is of type dataframe, which is a 2D data structure where columns can be of different types
type(data)

FileNotFoundError: [Errno 2] No such file or directory: 'titanic_short.csv'

[Tutorial for python data frames](https://stackabuse.com/beginners-tutorial-on-the-pandas-python-library/)

In [ ]:
# print using python system print
print(data)

In [ ]:
# print using pandas display
data

In [ ]:
data.head() # we can set the number of first rows to be displayed.
# guess what is the commmand for the tail

In [ ]:
# Same goes for tail

data.tail()

In [ ]:

#### Set specific cells:
data[10:19]

### Self excercise: Suggest how to display only survivors (denoted by 1)


In [ ]:
data[data['survived'] == 1]


### Self excercise: Suggest how to display only females gender

In [ ]:
data[data['sex']=='female']

# Self excercise: Suggest how to display only females survivors

In [ ]:
data[(data['survived'] == 1) & (data['sex']=='female')]

In [ ]:
#### display some of the collumns by a list of collumns
data[ [ 'pclass','age'] ] 

In [ ]:
#### Number of rows and collumns by hsape attribute:
data.shape

In [ ]:
#### Get more information such as the column names by info() method
data.info()

In [ ]:
#### the type of the read data is data frame
type(data)

## Add nice equations using LaTEX syntax in Markdown
### Sphere or Quadratic equations::
$ x^2 + y^2 = z^2 \\$
$ \\ x_1,_2 =  \frac{- b\pm \sqrt{b^2-4ac}}{2a} $

## Numpy
Matrices and much more, this is where the fun begins..

[Numpy official docs](https://numpy.org/doc/stable/reference/index.html)

In [8]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr*arr)

[ 1  4  9 16 25]


In [9]:
#### vector multiplication (AKA dot producdt)
print("arr.dot(arr)\t=",arr.dot(arr))
# or by 
print("arr@arr\t\t=",arr@arr)


arr.dot(arr)	= 55
arr@arr		= 55


In [10]:
# create ones matrix of specific size:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# self excercise: create zeros matrix of specific size:




In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# we can create any constant array
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [14]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# self excercise: create a 3X3 matrix where digonal has value of 8






In [16]:
8*np.eye(3)

array([[8., 0., 0.],
       [0., 8., 0.],
       [0., 0., 8.]])

In [22]:
e = np.random.random((2,4)) 
print(e)

[[0.21763861 0.91912039 0.64856454 0.68660837]
 [0.37050684 0.37090226 0.96263439 0.99146131]]


### Self learning at home:
+ 1. Read the tutorials in links
+ 2. Write a NumPy program to test whether none of the elements of a given array is zero (create a sample array).

In [15]:
import numpy as np
x = np.array([1, 2, 3, 4])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([0, 1, 2, 3])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False
