# Tirgul 4
I this session, we will 

In [1]:
# tirgul4
# random
import numpy as np
h,w = 2,4
e = np.random.random((h,w)) 
print("Random Matrix dim: {}X{}".format(h,w))
print(e)

Random Matrix dim: 2X4
[[0.48689345 0.72884002 0.12550436 0.18759066]
 [0.50192448 0.53524207 0.99909107 0.61606466]]


In [2]:
numCols = 6
grades = np.random.randint(70,100,size=(10,numCols))
print("Random Grades:")
print(grades)

Random Grades:
[[86 76 79 79 80 97]
 [96 86 82 90 77 78]
 [76 76 70 92 98 76]
 [95 88 99 74 92 74]
 [93 79 84 72 80 82]
 [74 74 93 73 83 89]
 [79 85 87 93 98 79]
 [78 72 77 85 81 87]
 [81 87 76 83 87 79]
 [72 81 97 84 99 81]]


In [3]:
# Calculate the average of the top 5 grades for each student
top5Avg = (grades.sum(axis=1)-grades.min(axis=1)) / (numCols-1)
top5Avg
top5Avg = top5Avg.reshape(len(top5Avg),1) # for display purpose
print(top5Avg)

[[84.2]
 [86.4]
 [83.6]
 [89.6]
 [83.6]
 [82.6]
 [88.4]
 [81.6]
 [83.4]
 [88.4]]


In [4]:
# let's read it using pandas
import pandas as pd
url = 'https://raw.githubusercontent.com/nlihin/data-analytics/main/datasets/italy-covid-daywise.csv'
covid_df = pd.read_csv(url)
covid_df.tail()

date  new_cases  new_deaths  new_tests
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

### Let's focus on date column

In [5]:
covid_df["date"]

0      2019-12-31
1      2020-01-01
2      2020-01-02
3      2020-01-03
4      2020-01-04
          ...    
243    2020-08-30
244    2020-08-31
245    2020-09-01
246    2020-09-02
247    2020-09-03
Name: date, Length: 248, dtype: object

- Note that date type is object. let's convert it to pandas datetime
- For pandas datetime reference and examples: [link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html)
- Video tutorial: [youtube link](https://www.youtube.com/watch?v=UFuo7EHI8zc)


In [11]:
covid_df.date = pd.to_datetime(covid_df.date)
covid_df.date

0     2019-12-31
1     2020-01-01
2     2020-01-02
3     2020-01-03
4     2020-01-04
         ...    
243   2020-08-30
244   2020-08-31
245   2020-09-01
246   2020-09-02
247   2020-09-03
Name: date, Length: 248, dtype: datetime64[ns]

Now we can extract the year,month,day and weekday properties (and muchmore - for ) 

In [12]:
covid_df['year'] = pd.DatetimeIndex(covid_df.date).year
covid_df['month'] = pd.DatetimeIndex(covid_df.date).month
covid_df['day'] = pd.DatetimeIndex(covid_df.date).day
covid_df['weekday'] = pd.DatetimeIndex(covid_df.date).weekday
covid_df

date  new_cases  new_deaths  new_tests  year  month  day  weekday
0   2019-12-31        0.0         0.0        NaN  2019     12   31        1
1   2020-01-01        0.0         0.0        NaN  2020      1    1        2
2   2020-01-02        0.0         0.0        NaN  2020      1    2        3
3   2020-01-03        0.0         0.0        NaN  2020      1    3        4
4   2020-01-04        0.0         0.0        NaN  2020      1    4        5
..         ...        ...         ...        ...   ...    ...  ...      ...
243 2020-08-30     1444.0         1.0    53541.0  2020      8   30        6
244 2020-08-31     1365.0         4.0    42583.0  2020      8   31        0
245 2020-09-01      996.0         6.0    54395.0  2020      9    1        1
246 2020-09-02      975.0         8.0        NaN  2020      9    2        2
247 2020-09-03     1326.0         6.0        NaN  2020      9    3        3

[248 rows x 8 columns]

Now we can present rows of specific dates, for example only August:

In [19]:
covid_df_august = covid_df[covid_df.month == 8]
covid_df_august.head()

date  new_cases  new_deaths  new_tests  year  month  day  weekday
214 2020-08-01      379.0         9.0    31905.0  2020      8    1        5
215 2020-08-02      295.0         5.0    24496.0  2020      8    2        6
216 2020-08-03      238.0         8.0    13467.0  2020      8    3        0
217 2020-08-04      159.0        12.0    23491.0  2020      8    4        1
218 2020-08-05      190.0         5.0    29739.0  2020      8    5        2

### Extract the subset of columns to be aggregated

In [22]:
covid_df_august_metrics = covid_df_august[['new_cases', 'new_deaths', 'new_tests']]

# Get the column-wise sum
covid_august_totals = covid_df_august_metrics.sum()
covid_august_totals

new_cases       21060.0
new_deaths        345.0
new_tests     1098704.0
dtype: float64

We can do the same for mean 

In [16]:
covid_df_august_metrics.mean()

new_cases       679.354839
new_deaths       11.129032
new_tests     35442.064516
dtype: float64

Or median

In [19]:
covid_df_august_metrics.median()

new_cases       522.0
new_deaths        6.0
new_tests     31905.0
dtype: float64

### The *groupby* command

In [30]:
# let's sum:
covid_month_df_sum = covid_df.groupby('month')[['new_cases', 'new_deaths', 'new_tests']].mean()




covid_month_df_sum
# deaths per months graphs
# hist cborn

new_cases  new_deaths     new_tests
month                                       
1         0.096774    0.000000           NaN
2        30.517241    0.724138           NaN
3      3253.258065  373.225806           NaN
4      3395.066667  536.366667  38144.636364
5       937.838710  182.516129  34797.419355
6       259.066667   46.800000  27678.466667
7       216.838710   12.516129  25732.000000
8       679.354839   11.129032  35442.064516
9      1099.000000    6.666667  54395.000000
12        0.000000    0.000000           NaN

We could do the same for mean or any other stats

In [25]:
covid_df.groupby('month')[['new_cases', 'new_deaths', 'new_tests']].mean()

new_cases  new_deaths     new_tests
month                                       
1         0.096774    0.000000           NaN
2        30.517241    0.724138           NaN
3      3253.258065  373.225806           NaN
4      3395.066667  536.366667  38144.636364
5       937.838710  182.516129  34797.419355
6       259.066667   46.800000  27678.466667
7       216.838710   12.516129  25732.000000
8       679.354839   11.129032  35442.064516
9      1099.000000    6.666667  54395.000000
12        0.000000    0.000000           NaN

### Print todays date in pandas:

In [26]:
import pandas as pd
from datetime import date # get python datetime
now = pd.to_datetime(str(date.today()), format='%Y-%m-%d')
print("Today's date:")
print(now)

Today's date:
2021-04-06 00:00:00


## Self Learning:.
1. calculate total deaths at May in attached *'italy-covid-daywise.csv'* fuke
1. python pandas datetime excercises (with solutions): [Link to exercises](https://www.w3resource.com/python-exercises/pandas/datetime/index.php)

## Solution 2

In [27]:
import pandas as pd
covid_df = pd.read_csv('italy-covid-daywise.csv')
covid_df['date'] = pd.to_datetime(covid_df.date)
covid_df['month'] = pd.DatetimeIndex(covid_df.date).month
totalDeathsInMay = covid_df[covid_df.month == 5]['new_deaths'].sum()
print('total deaths in May: ',totalDeathsInMay)

total deaths in May:  5658.0
